[package]
name = "egui-thematic-demo"
version = "0.1.1"
authors = ["Matthew Berger <matthewjordanberger@gmail.com>"]
edition = "2021"

[dependencies]
egui-thematic = { path = ".." }
nightshade = "0.6.7"
getrandom = { version = "0.2", features = ["js"] }
