[package]
name = "egui-thematic-demo"
version = "0.1.0"
authors = ["Matthew Berger <matthewjordanberger@gmail.com>"]
edition = "2021"

[dependencies]
egui-thematic = { path = ".." }
nightshade = { path = "../../nightshade/crates/nightshade" }
getrandom = { version = "0.2", features = ["js"] }
